# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

name: Updoc

on:
  workflow_dispatch: {}

jobs:
  publish-docs:
    uses: upbound/official-providers-ci/.github/workflows/provider-updoc.yml@cd6215984633723be29e7709f39e3a83aaeb0baf # standard-runners
    with:
      providers: "config"
      go-version: 1.22
    secrets:
      UPBOUND_CI_PROD_BUCKET_SA: ${{ secrets.UPBOUND_CI_PROD_BUCKET_SA }}
